language: r
sudo: false
warnings_are_errors: false
cache:
  packages: true
  directories:
    - node_modules
before_install:
  - npm install
script:
  - "./travis-tool.sh run_tests"
  - npm run test
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: ZtEA6qGKeTZsSR4cfPMKnzQhPjyrloE4jQ3n+yoWowh21+CVMhEZT49FalgjerE/1XvdDDcL5NgSABZJA/OsV2rBxc9eE+Lgm1aZiyvswxpMd10cw7Bfy9JjW17dfQ5Fyqu7kR6iwQAqOPafaoJjjesJWhjDom/U+tYdYfXrHkg=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
